<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InterpretationGuideTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $interpretation_guides = [
            [
            'indicator_id'=> 1,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 1,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 2,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 2,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 3,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 3,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 4,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 4,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 5,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 5,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 6,
            'type'=> 0,
            'text'=> 'Las policías pueden estar realizando detenciones sin observar los supuestos permitidos por la CPEUM y el CNPP.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 6,
            'type'=> 0,
            'text'=> 'Puede ser que no existe una buena coordinación entre el Agente del Ministerio Público y las policías, lo que está generando que los informes policiales no cumplan con los estándares que el Agente del Ministerio Público considera necesarios para ratificar la detención.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 6,
            'type'=> 1,
            'text'=> 'El Agente del Ministerio Público puede no estar haciendo una revisión estricta del informe policial con el que se pone a disposición al detenido.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 7,
            'type'=> 0,
            'text'=> 'El Agente del Ministerio Público puede no estar haciendo una revisión estricta del informe policial con el que se pone a disposición al detenido.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 7,
            'type'=> 1,
            'text'=> 'Puede ser que los jueces de control no estén haciendo una revisión estricta de las circunstancias de la detención, mostrándose resolviendo de una forma favorable al Agente del Ministerio Público.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 8,
            'type'=> 0,
            'text'=> 'Puede ser que el AMP no se sienta con la capacidad para acudir a la audiencia de control de detención.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 8,
            'type'=> 0,
            'text'=> 'Puede ser que la carga de trabajo le impida al Agente del Ministerio Público acudir a las audiencias de control de detención.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 8,
            'type'=> 0,
            'text'=> 'Puede ser que la Institución no cuente con una política de persecución penal que le permita priorizar los casos y el uso de los recursos disponibles.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 8,
            'type'=> 1,
            'text'=> 'Puede ser que la Institución no cuente con una política de persecución penal que le permita priorizar los casos y el uso de los recursos disponibles.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 9,
            'type'=> 0,
            'text'=> 'Puede ser que no exista una regulación interna, sustentada en la política de persecución penal, lo suficientemente clara como para hacer un uso jurídicamente adecuado y administrativamente razonable de las facultades discrecionales.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 9,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no haya sido adecuadamente capacitados para el dictado de este tipo de resoluciones.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 9,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público prefiera evitar el uso de este tipo de resoluciones con el objetivo de evitarse problemas con la víctima y/o su asesor jurídico.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 9,
            'type'=> 1,
            'text'=> 'Puede ser que no exista unaregulación interna, sustentada en la política de persecución penal, lo suficientemente clara como para hacer un uso jurídicamente adecuado y administrativamente razonable de las facultades discrecionales.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 9,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no haya sido adecuadamente capacitado para el dictado de este tipo de resoluciones.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 10,
            'type'=> 0,
            'text'=> 'Puede ser que a nivel institucional no se haya definido con claridad cuáles son las características que debe reunir un caso para considerar que no existe línea de investigación.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 10,
            'type'=> 0,
            'text'=> 'Puede ser que se estén utilizando otras formas de terminación de la investigación distintas a las que jurídicamente corresponden.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 10,
            'type'=> 1,
            'text'=> 'Puede ser que a nivel institucional no se haya definido con claridad cuáles son las características que debe reunir un caso para considerar que no existe línea de investigación.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 11,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no tenga claro cuáles son los supuestos en los que la ley lo faculta para dictar la abstención de la investigación.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 11,
            'type'=> 0,
            'text'=> 'Puede ser que se estén utilizando otras formas de terminación de la investigación distintas a las que jurídicamente corresponden.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 11,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no tenga claro cuáles son los supuestos en los que la ley lo faculta para dictar la abstención de la investigación.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 12,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no tenga claro cuáles son los supuestos en los que la ley lo faculta para dictar el no ejercicio de la acción penal.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 12,
            'type'=> 0,
            'text'=> 'Puede ser que la organización interna de la Institución obstaculice una aprobación de forma eficiente por parte del mando a cargo de autorizar el no ejercicio de la acción penal.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 12,
            'type'=> 0,
            'text'=> 'Puede ser que se estén utilizando otras formas de terminación de la investigación distintas a las que jurídicamente corresponden.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 12,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no tenga claro cuáles son los supuestos en los que la ley lo faculta para dictar el no ejercicio de la acción penal.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 13,
            'type'=> 0,
            'text'=> 'Puede ser que la Institución no haya expedido los lineamientos para el uso de los criterios de oportunidad.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 13,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no tenga claro cuáles son los supuestos en los que la ley lo faculta para dictar los criterios de oportunidad.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 13,
            'type'=> 0,
            'text'=> 'Puede ser que se estén utilizando otras formas de terminación de la investigación distintas a las que jurídicamente corresponden.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 13,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no tenga claro cuáles son los supuestos en los que la ley lo faculta para dictar el no ejercicio de la acción penal.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 14,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 14,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 15,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no conozca en qué consisten los acuerdos reparatorios y los mecanismos alternativos para la solución de controversias y que por lo tanto no pueda realizar una adecuada promoción de los mismos ante las partes',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 15,
            'type'=> 0,
            'text'=> 'Puede ser que la Institución no cuente con procedimientos adecuados que permitan un uso oportuno de los acuerdos reparatorios.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 15,
            'type'=> 0,
            'text'=> 'Puede ser que la defensa se esté oponiendo injustificadamente a la celebración del acuerdo reparatorio.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 15,
            'type'=> 1,
            'text'=> 'Puede ser que se estén celebrando acuerdos reparatorios en asuntos en que jurídicamente no son procedentes.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 15,
            'type'=> 1,
            'text'=> 'Puede ser que se esté coaccionando a las partes para lograr la celebración de los acuerdos reparatorios.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 16,
            'type'=> 0,
            'text'=> 'Puede ser que el órgano MASC no cuente con una capacidad suficiente como para atender la carga de trabajo enviada por el Agente del Ministerio Público.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 16,
            'type'=> 0,
            'text'=> 'Puede ser que los Agentes del Ministerio Público perciban que el órgano MASC no es eficaz en las resoluciones de los asuntos.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 16,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público considere que para celebrar un acuerdo reparatorio es imprescindible enviarlo al órgano MASC.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 16,
            'type'=> 1,
            'text'=> 'Puede ser que la Institución haya establecido como requisito el envío al órgano MASC de todos los asuntos susceptibles de ser resueltos mediante acuerdos reparatorios.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 17,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no se sienta con la capacidad para acudir a la audiencia de formulación de imputación.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 17,
            'type'=> 0,
            'text'=> 'Puede ser que la carga de trabajo le impida al Agente del Ministerio Público acudir a las audiencias de control de detención.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 17,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público aún no tenga claro el estándar probatorio que se requiere para la vinculación a proceso.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 17,
            'type'=> 0,
            'text'=> 'Puede ser que la Institución no cuente con una política de persecución penal que le permita priorizar los casos y el uso de los recursos disponibles',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 17,
            'type'=> 1,
            'text'=> 'Puede ser que la Institución no cuente con una política de persecución penal que le permita al Agente del Ministerio Púbico priorizar los casos y el uso de los recursos disponibles',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 18,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no tenga la capacidad para demostrar que la investigación indica que existen datos de que se ha cometido un hecho que la ley señala como delito y la probable autoría o participación del imputado.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 18,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público aún no tenga claro el estándar probatorio que se requiere para la vinculación a proceso.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 18,
            'type'=> 1,
            'text'=> 'Puede ser que los jueces de control no estén haciendo una revisión estricta del estándar probatorio que se requieren para la vinculación a proceso o bien sin considerar, inclinándose a resolver a favor del Agente del Ministerio Público.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 19,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no comprenda adecuadamente la función de las medidas cautelares.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 19,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no comprenda la utilidad de las distintas opciones que hay entre el catálogo de medidas cautelares.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 19,
            'type'=> 1,
            'text'=> 'No tendría implicación alguna',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 20,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no logre probar ante el Juez de Control la necesidad y proporcionalidad de la medida.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 20,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público observa la prisión preventiva como una forma de combate a la impunidad.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 20,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no comprenda la relación entre el principio de presunción de inocencia y la prisión preventiva.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 20,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no comprenda los principios de necesidad y proporcionalidad que se deben observar en la imposición de todas las medidas cautelares, especialmente en la de prisión preventiva.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 20,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público considera que conseguir un mayor número de prisiones preventivas puede ser percibido como algo positivo por sus superiores jerárquicos.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 20,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público esté logrando la vinculación a proceso preponderantemente en delitos de prisión preventiva oficiosa.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 20,
            'type'=> 1,
            'text'=> 'Puede ser que el Juez de Control no esté haciendo una revisión estricta de la solicitud del Agente del Ministerio Público, inclinándose a resolver a favor de éste',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 21,
            'type'=> 0,
            'text'=> 'Toda vez que este indicador es complementario con el anterior, para su interpretación se deben observar las interpretaciones contenidas en el indicador de prisión preventiva.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 21,
            'type'=> 1,
            'text'=> 'Toda vez que este indicador es complementario con el anterior, para su interpretación se deben observar las interpretaciones contenidas en el indicador de prisión preventiva.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 22,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no conozca en qué consisten los acuerdos reparatorios y los mecanismos alternativos para la solución de controversias y que por lo tanto no pueda realizar una adecuada promoción de los mismos antes las partes.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 22,
            'type'=> 0,
            'text'=> 'Puede ser que la Institución no cuente con procedimientos adecuados que permitan el uso de los acuerdos reparatorios.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 22,
            'type'=> 0,
            'text'=> 'Puede ser que la defensa se esté oponiendo injustificadamente a la celebración del acuerdo reparatorio.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 22,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no esté utilizando los acuerdos reparatorios de forma oportuna en la investigación inicial.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 22,
            'type'=> 1,
            'text'=> 'Puede ser que se estén celebrando acuerdos reparatorios en asuntos en que jurídicamente no son procedentes.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 22,
            'type'=> 1,
            'text'=> 'Puede ser que se esté coaccionando a las partes para lograr la celebración de los acuerdos reparatorios.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 23,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no conozca en qué consiste la suspensión condicional del proceso y que por lo tanto no pueda realizar una adecuada promoción de la misma entre las partes.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 23,
            'type'=> 0,
            'text'=> 'Puede ser que la Institución no cuente con procedimientos adecuados que permitan el uso de la suspensión condicional del proceso.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 23,
            'type'=> 0,
            'text'=> 'Puede ser que la defensa se esté oponiendo injustificadamente a la celebración de la suspensión condicional del proceso.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 23,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público prefiera evitar el uso de la suspensión condicional con el objetivo de evitarse problemas con la víctima y/o su asesor jurídico.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 23,
            'type'=> 1,
            'text'=> 'Puede ser que se estén celebrando suspensiones condicionales en asuntos en que jurídicamente no son procedentes.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 23,
            'type'=> 1,
            'text'=> 'Puede ser que se esté coaccionando a las partes para lograr la celebración de los acuerdos reparatorios.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 24,
            'type'=> 0,
            'text'=> 'Puede ser que la defensa se esté oponiendo injustificadamente al procedimiento abreviado.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 24,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público esté ofreciendo penas muy altas.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 24,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público prefiera evitar el uso del procedimiento abreviado con el objetivo de evitarse problemas con la víctima y/o su asesor jurídico.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 24,
            'type'=> 1,
            'text'=> 'Puede ser que la institución no cuente con una política clara respecto de la resolución de casos mediante procedimiento abreviado, haciendo un uso excesivo de la medida.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 24,
            'type'=> 1,
            'text'=> 'Puede que el Agente del Ministerio Público no se sienta con la capacidad para acudir a la audiencia de juicio oral.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 24,
            'type'=> 1,
            'text'=> 'Puede ser que se está coaccionando al imputado para la celebración del procedimiento abreviado.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 25,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 25,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 26,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 26,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 27,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 27,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 28,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 28,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 29,
            'type'=> 0,
            'text'=> 'Puede ser que el Agente del Ministerio Público no esté realizando de forma adecuada la investigación y prefiera no acudir a la audiencia de juicio oral.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 29,
            'type'=> 1,
            'text'=> 'Puede ser que el Agente del Ministerio Público no esté utilizando adecuadamente las soluciones alternas o el procedimiento abreviado.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 30,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 30,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 31,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 31,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 32,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 32,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 33,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 33,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 34,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 34,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 35,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 35,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 36,
            'type'=> 0,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
            'indicator_id'=> 36,
            'type'=> 1,
            'text'=> 'N.A.',
            'created_at'=> Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ];

        DB::table('interpretation_guides')->insert($interpretation_guides);
    }
}
