<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SociodemographicContextTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'state_id'=> 1,
                'variable1'=> 1321453,
                'clasification1'=> 27,
                'variable2'=> 5589,
                'clasification2'=> 28,
                'variable3'=> 236,
                'clasification3'=> 5,
                'variable4'=> 283073,
                'clasification4'=> 25,
                'variable5'=> 214213,
                'clasification5'=> 8,
                'variable6'=> 9.7,
                'clasification6'=> 7,
                'variable7'=> 13.77,
                'clasification7'=> 11,
                'variable8'=> 28.2,
                'clasification8'=> 7,
                'variable9'=> -0.889,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 5,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 2,
                'variable1'=> 3584605,
                'clasification1'=> 14,
                'variable2'=> 70113,
                'clasification2'=> 12,
                'variable3'=> 51,
                'clasification3'=> 20,
                'variable4'=> 695759,
                'clasification4'=> 11,
                'variable5'=> 194096,
                'clasification5'=> 11,
                'variable6'=> 9.8,
                'clasification6'=> 6,
                'variable7'=> 18.1,
                'clasification7'=> 25,
                'variable8'=> 22.2,
                'clasification8'=> 3,
                'variable9'=> -1.102,
                'variable9_s1'=> 'Muy bajo',
                'clasification9'=> 3,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 3,
                'variable1'=> 809833,
                'clasification1'=> 31,
                'variable2'=> 73677,
                'clasification2'=> 9,
                'variable3'=> 11,
                'clasification3'=> 32,
                'variable4'=> 187237,
                'clasification4'=> 29,
                'variable5'=> 231204,
                'clasification5'=> 7,
                'variable6'=> 9.9,
                'clasification6'=> 4,
                'variable7'=> 12.76,
                'clasification7'=> 6,
                'variable8'=> 22.1,
                'clasification8'=> 2,
                'variable9'=> -0.598,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 11,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 4,
                'variable1'=> 935047,
                'clasification1'=> 30,
                'variable2'=> 51833,
                'clasification2'=> 18,
                'variable3'=> 18,
                'clasification3'=> 29,
                'variable4'=> 494278,
                'clasification4'=> 14,
                'variable5'=> 528613,
                'clasification5'=> 1,
                'variable6'=> 9.1,
                'clasification6'=> 20,
                'variable7'=> 12.35,
                'clasification7'=> 4,
                'variable8'=> 43.8,
                'clasification8'=> 19,
                'variable9'=> 0.463,
                'variable9_s1'=> 'Alto',
                'clasification9'=> 23,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 5,
                'variable1'=> 3029740,
                'clasification1'=> 16,
                'variable2'=> 151571,
                'clasification2'=> 3,
                'variable3'=> 20,
                'clasification3'=> 28,
                'variable4'=> 774610,
                'clasification4'=> 7,
                'variable5'=> 255669,
                'clasification5'=> 4,
                'variable6'=> 9.9,
                'clasification6'=> 4,
                'variable7'=> 13.75,
                'clasification7'=> 10,
                'variable8'=> 24.8,
                'clasification8'=> 4,
                'variable9'=> -1.101,
                'variable9_s1'=> 'Muy bajo',
                'clasification9'=> 4,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 6,
                'variable1'=> 747801,
                'clasification1'=> 32,
                'variable2'=> 5455,
                'clasification2'=> 29,
                'variable3'=> 137,
                'clasification3'=> 10,
                'variable4'=> 127814,
                'clasification4'=> 31,
                'variable5'=> 170920,
                'clasification5'=> 14,
                'variable6'=> 9.5,
                'clasification6'=> 11,
                'variable7'=> 13.36,
                'clasification7'=> 9,
                'variable8'=> 33.6,
                'clasification8'=> 14,
                'variable9'=> -0.730,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 7,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 7,
                'variable1'=> 5382083,
                'clasification1'=> 7,
                'variable2'=> 73887,
                'clasification2'=> 8,
                'variable3'=> 73,
                'clasification3'=> 16,
                'variable4'=> 332092,
                'clasification4'=> 20,
                'variable5'=> 61703,
                'clasification5'=> 32,
                'variable6'=> 7.3,
                'clasification6'=> 32,
                'variable7'=> 18.84,
                'clasification7'=> 27,
                'variable8'=> 77.1,
                'clasification8'=> 32,
                'variable9'=> 2.406,
                'variable9_s1'=> 'Muy alto',
                'clasification9'=> 31,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 8,
                'variable1'=> 3782018,
                'clasification1'=> 11,
                'variable2'=> 247087,
                'clasification2'=> 1,
                'variable3'=> 15,
                'clasification3'=> 31,
                'variable4'=> 706773,
                'clasification4'=> 10,
                'variable5'=> 186877,
                'clasification5'=> 12,
                'variable6'=> 9.5,
                'clasification6'=> 11,
                'variable7'=> 11.94,
                'clasification7'=> 2,
                'variable8'=> 30.6,
                'clasification8'=> 9,
                'variable9'=> -0.599,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 10,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 9,
                'variable1'=> 8811266,
                'clasification1'=> 2,
                'variable2'=> 1499,
                'clasification2'=> 32,
                'variable3'=> 5878,
                'clasification3'=> 1,
                'variable4'=> 3409016,
                'clasification4'=> 1,
                'variable5'=> 386893,
                'clasification5'=> 2,
                'variable6'=> 11.1,
                'clasification6'=> 1,
                'variable7'=> 19.07,
                'clasification7'=> 29,
                'variable8'=> 27.6,
                'clasification8'=> 5,
                'variable9'=> -1.451,
                'variable9_s1'=> 'Muy bajo',
                'clasification9'=> 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 10,
                'variable1'=> 1799320,
                'clasification1'=> 24,
                'variable2'=> 73677,
                'clasification2'=> 9,
                'variable3'=> 24,
                'clasification3'=> 26,
                'variable4'=> 249247,
                'clasification4'=> 26,
                'variable5'=> 138523,
                'clasification5'=> 19,
                'variable6'=> 9.1,
                'clasification6'=> 20,
                'variable7'=> 15.37,
                'clasification7'=> 17,
                'variable8'=> 36,
                'clasification8'=> 15,
                'variable9'=> 0.049,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 20,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 11,
                'variable1'=> 17363387,
                'clasification1'=> 1,
                'variable2'=> 21461,
                'clasification2'=> 25,
                'variable3'=> 809,
                'clasification3'=> 2,
                'variable4'=> 1855140,
                'clasification4'=> 2,
                'variable5'=> 106842,
                'clasification5'=> 28,
                'variable6'=> 9.5,
                'clasification6'=> 11,
                'variable7'=> 19.91,
                'clasification7'=> 31,
                'variable8'=> 47.9,
                'clasification8'=> 21,
                'variable9'=> -0.567,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 12,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 12,
                'variable1'=> 5908845,
                'clasification1'=> 6,
                'variable2'=> 30589,
                'clasification2'=> 22,
                'variable3'=> 193,
                'clasification3'=> 6,
                'variable4'=> 914368,
                'clasification4'=> 6,
                'variable5'=> 154746,
                'clasification5'=> 17,
                'variable6'=> 8.4,
                'clasification6'=> 27,
                'variable7'=> 14.17,
                'clasification7'=> 12,
                'variable8'=> 42.4,
                'clasification8'=> 18,
                'variable9'=> -0.072,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 18,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 13,
                'variable1'=> 3607210,
                'clasification1'=> 13,
                'variable2'=> 63794,
                'clasification2'=> 14,
                'variable3'=> 57,
                'clasification3'=> 17,
                'variable4'=> 287625,
                'clasification4'=> 24,
                'variable5'=> 79736,
                'clasification5'=> 30,
                'variable6'=> 7.8,
                'clasification6'=> 30,
                'variable7'=> 16.44,
                'clasification7'=> 20,
                'variable8'=> 64.4,
                'clasification8'=> 30,
                'variable9'=> 2.557,
                'variable9_s1'=> 'Muy alto',
                'clasification9'=> 32,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 14,
                'variable1'=> 2947206,
                'clasification1'=> 18,
                'variable2'=> 20987,
                'clasification2'=> 26,
                'variable3'=> 140,
                'clasification3'=> 9,
                'variable4'=> 338706,
                'clasification4'=> 19,
                'variable5'=> 114924,
                'clasification5'=> 25,
                'variable6'=> 8.7,
                'clasification6'=> 24,
                'variable7'=> 18.29,
                'clasification7'=> 26,
                'variable8'=> 50.6,
                'clasification8'=> 24,
                'variable9'=> 0.496,
                'variable9_s1'=> 'Alto',
                'clasification9'=> 24,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 15,
                'variable1'=> 8110943,
                'clasification1'=> 4,
                'variable2'=> 80137,
                'clasification2'=> 5,
                'variable3'=> 101,
                'clasification3'=> 12,
                'variable4'=> 1466416,
                'clasification4'=> 4,
                'variable5'=> 180795,
                'clasification5'=> 13,
                'variable6'=> 9.2,
                'clasification6'=> 18,
                'variable7'=> 17.13,
                'clasification7'=> 24,
                'variable8'=> 31.8,
                'clasification8'=> 12,
                'variable9'=> -0.82,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 6,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 16,
                'variable1'=> 4658159,
                'clasification1'=> 9,
                'variable2'=> 59864,
                'clasification2'=> 16,
                'variable3'=> 78,
                'clasification3'=> 15,
                'variable4'=> 526910,
                'clasification4'=> 13,
                'variable5'=> 113116,
                'clasification5'=> 27,
                'variable6'=> 7.9,
                'clasification6'=> 29,
                'variable7'=> 23.12,
                'clasification7'=> 32,
                'variable8'=> 55.3,
                'clasification8'=> 27,
                'variable9'=> 0.498,
                'variable9_s1'=> 'Alto',
                'clasification9'=> 25,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 17,
                'variable1'=> 1965487,
                'clasification1'=> 23,
                'variable2'=> 4941,
                'clasification2'=> 30,
                'variable3'=> 398,
                'clasification3'=> 3,
                'variable4'=> 241633,
                'clasification4'=> 27,
                'variable5'=> 122938,
                'clasification5'=> 22,
                'variable6'=> 9.3,
                'clasification6'=> 15,
                'variable7'=> 16.06,
                'clasification7'=> 19,
                'variable8'=> 49.5,
                'clasification8'=> 23,
                'variable9'=> -0.199,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 16,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 18,
                'variable1'=> 1268460,
                'clasification1'=> 29,
                'variable2'=> 27621,
                'clasification2'=> 23,
                'variable3'=> 46,
                'clasification3'=> 21,
                'variable4'=> 150506,
                'clasification4'=> 30,
                'variable5'=> 118653,
                'clasification5'=> 23,
                'variable6'=> 9.2,
                'clasification6'=> 18,
                'variable7'=> 15.97,
                'clasification7'=> 18,
                'variable8'=> 37.5,
                'clasification8'=> 16,
                'variable9'=> 0.314,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 22,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 19,
                'variable1'=> 5229492,
                'clasification1'=> 8,
                'variable2'=> 64555,
                'clasification2'=> 13,
                'variable3'=> 81,
                'clasification3'=> 14,
                'variable4'=> 1559139,
                'clasification4'=> 3,
                'variable5'=> 298143,
                'clasification5'=> 3,
                'variable6'=> 10.3,
                'clasification6'=> 2,
                'variable7'=> 12.34,
                'clasification7'=> 3,
                'variable8'=> 14.2,
                'clasification8'=> 1,
                'variable9'=> -1.389,
                'variable9_s1'=> 'Muy bajo',
                'clasification9'=> 2,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 20,
                'variable1'=> 4061497,
                'clasification1'=> 10,
                'variable2'=> 95364,
                'clasification2'=> 4,
                'variable3'=> 43,
                'clasification3'=> 24,
                'variable4'=> 305450,
                'clasification4'=> 22,
                'variable5'=> 75206,
                'clasification5'=> 31,
                'variable6'=> 7.5,
                'clasification6'=> 31,
                'variable7'=> 16.86,
                'clasification7'=> 22,
                'variable8'=> 70.4,
                'clasification8'=> 31,
                'variable9'=> 2.123,
                'variable9_s1'=> 'Muy alto',
                'clasification9'=> 30,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 21,
                'variable1'=> 6313789,
                'clasification1'=> 5,
                'variable2'=> 33919,
                'clasification2'=> 21,
                'variable3'=> 186,
                'clasification3'=> 7,
                'variable4'=> 715143,
                'clasification4'=> 8,
                'variable5'=> 113267,
                'clasification5'=> 26,
                'variable6'=> 8.5,
                'clasification6'=> 26,
                'variable7'=> 18.92,
                'clasification7'=> 28,
                'variable8'=> 59.4,
                'clasification8'=> 28,
                'variable9'=> 0.686,
                'variable9_s1'=> 'Alto',
                'clasification9'=> 28,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 22,
                'variable1'=> 2063148,
                'clasification1'=> 22,
                'variable2'=> 11769,
                'clasification2'=> 27,
                'variable3'=> 175,
                'clasification3'=> 8,
                'variable4'=> 484806,
                'clasification4'=> 16,
                'variable5'=> 234984,
                'clasification5'=> 6,
                'variable6'=> 9.6,
                'clasification6'=> 8,
                'variable7'=> 12.87,
                'clasification7'=> 7,
                'variable8'=> 31.1,
                'clasification8'=> 11,
                'variable9'=> -0.491,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 13,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 23,
                'variable1'=> 1664667,
                'clasification1'=> 25,
                'variable2'=> 50350,
                'clasification2'=> 19,
                'variable3'=> 33,
                'clasification3'=> 25,
                'variable4'=> 327104,
                'clasification4'=> 21,
                'variable5'=> 196498,
                'clasification5'=> 10,
                'variable6'=> 9.6,
                'clasification6'=> 8,
                'variable7'=> 16.48,
                'clasification7'=> 21,
                'variable8'=> 28.8,
                'clasification8'=> 8,
                'variable9'=> -0.375,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 14,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 24,
                'variable1'=> 2801839,
                'clasification1'=> 19,
                'variable2'=> 62848,
                'clasification2'=> 15,
                'variable3'=> 45,
                'clasification3'=> 23,
                'variable4'=> 450391,
                'clasification4'=> 18,
                'variable5'=> 160748,
                'clasification5'=> 16,
                'variable6'=> 8.8,
                'clasification6'=> 22,
                'variable7'=> 9.83,
                'clasification7'=> 1,
                'variable8'=> 45.5,
                'clasification8'=> 20,
                'variable9'=> 0.578,
                'variable9_s1'=> 'Alto',
                'clasification9'=> 27,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 25,
                'variable1'=> 3034942,
                'clasification1'=> 15,
                'variable2'=> 58092,
                'clasification2'=> 17,
                'variable3'=> 52,
                'clasification3'=> 19,
                'variable4'=> 457553,
                'clasification4'=> 17,
                'variable5'=> 150762,
                'clasification5'=> 18,
                'variable6'=> 9.6,
                'clasification6'=> 8,
                'variable7'=> 14.69,
                'clasification7'=> 13,
                'variable8'=> 30.8,
                'clasification8'=> 10,
                'variable9'=> -0.242,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 15,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 26,
                'variable1'=> 3011810,
                'clasification1'=> 17,
                'variable2'=> 184934,
                'clasification2'=> 2,
                'variable3'=> 16,
                'clasification3'=> 30,
                'variable4'=> 712851,
                'clasification4'=> 9,
                'variable5'=> 236685,
                'clasification5'=> 5,
                'variable6'=> 10,
                'clasification6'=> 3,
                'variable7'=> 13.33,
                'clasification7'=> 8,
                'variable8'=> 27.9,
                'clasification8'=> 6,
                'variable9'=> -0.701,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 8,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 27,
                'variable1'=> 2431339,
                'clasification1'=> 20,
                'variable2'=> 24661,
                'clasification2'=> 24,
                'variable3'=> 99,
                'clasification3'=> 13,
                'variable4'=> 489407,
                'clasification4'=> 15,
                'variable5'=> 201291,
                'clasification5'=> 9,
                'variable6'=> 9.3,
                'clasification6'=> 15,
                'variable7'=> 17.1,
                'clasification7'=> 23,
                'variable8'=> 50.9,
                'clasification8'=> 25,
                'variable9'=> 0.304,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 21,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 28,
                'variable1'=> 3622605,
                'clasification1'=> 12,
                'variable2'=> 79829,
                'clasification2'=> 6,
                'variable3'=> 45,
                'clasification3'=> 22,
                'variable4'=> 607890,
                'clasification4'=> 12,
                'variable5'=> 167805,
                'clasification5'=> 15,
                'variable6'=> 9.5,
                'clasification6'=> 11,
                'variable7'=> 15.02,
                'clasification7'=> 16,
                'variable8'=> 32.2,
                'clasification8'=> 13,
                'variable9'=> -0.616,
                'variable9_s1'=> 'Bajo',
                'clasification9'=> 9,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 29,
                'variable1'=> 1313067,
                'clasification1'=> 28,
                'variable2'=> 3914,
                'clasification2'=> 31,
                'variable3'=> 335,
                'clasification3'=> 4,
                'variable4'=> 115400,
                'clasification4'=> 32,
                'variable5'=> 87886,
                'clasification5'=> 29,
                'variable6'=> 9.3,
                'clasification6'=> 15,
                'variable7'=> 14.84,
                'clasification7'=> 14,
                'variable8'=> 53.9,
                'clasification8'=> 26,
                'variable9'=> -0.198,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 17,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 30,
                'variable1'=> 8163963,
                'clasification1'=> 3,
                'variable2'=> 72815,
                'clasification2'=> 11,
                'variable3'=> 112,
                'clasification3'=> 11,
                'variable4'=> 940217,
                'clasification4'=> 5,
                'variable5'=> 115167,
                'clasification5'=> 24,
                'variable6'=> 8.2,
                'clasification6'=> 28,
                'variable7'=> 19.21,
                'clasification7'=> 30,
                'variable8'=> 62.2,
                'clasification8'=> 29,
                'variable9'=> 1.141,
                'variable9_s1'=> 'Alto',
                'clasification9'=> 29,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 31,
                'variable1'=> 2172839,
                'clasification1'=> 21,
                'variable2'=> 39340,
                'clasification2'=> 20,
                'variable3'=> 55,
                'clasification3'=> 18,
                'variable4'=> 300411,
                'clasification4'=> 23,
                'variable5'=> 138257,
                'clasification5'=> 20,
                'variable6'=> 8.8,
                'clasification6'=> 22,
                'variable7'=> 14.91,
                'clasification7'=> 15,
                'variable8'=> 41.9,
                'clasification8'=> 17,
                'variable9'=> 0.514,
                'variable9_s1'=> 'Alto',
                'clasification9'=> 26,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'state_id'=> 32,
                'variable1'=> 1600412,
                'clasification1'=> 26,
                'variable2'=> 75040,
                'clasification2'=> 7,
                'variable3'=> 21,
                'clasification3'=> 27,
                'variable4'=> 197171,
                'clasification4'=> 28,
                'variable5'=> 123200,
                'clasification5'=> 21,
                'variable6'=> 8.6,
                'clasification6'=> 25,
                'variable7'=> 12.37,
                'clasification7'=> 5,
                'variable8'=> 49,
                'clasification8'=> 22,
                'variable9'=> 0.01,
                'variable9_s1'=> 'Medio',
                'clasification9'=> 19,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ]
        ];

        DB::table('sociodemographic_contexts')->insert($data);
    }
}
